### ISSUE TITLE
LlamaParse not processing PDFs. Possible rate limit?

### ISSUE THREAD

**Issue by nick-kang** [run-llama/llama_cloud_services#392]
Error message: `Failed to parse the file`.

Job IDs:
a6ca6e76-b620-4c8f-b96b-278a34fe1863
76ed0142-8e79-43cb-95b4-70b255b6cec7
e43c6b75-cb9d-4e20-ae58-12457fac2f0a
383578a3-d3c5-4702-a760-bd41327583f2
56534389-68fe-47aa-8263-34d7af43fd61
362a25b0-f932-42ee-b610-29d508dbccee
47f14b01-ce6b-4ccb-9c3c-c568768fdd69
94ecba8a-9268-423d-a7f2-348c0414053f

The PDFs were sent to LllamaParse at the same time using the API. Is it possible to get more info on what the error was? I think it's a rate limit issue, but would like to confirm.

**Comment by hexapode** [comment]
We had an outage today (https://llamaindex.statuspage.io/) that have impact llama_parse cluster, and led to a few thousand job failing. Could you retry your query and validate it is still failing.
